name: Deploy to Main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          set -eu
          mkdir "$HOME/.ssh"
          echo "${{ secrets.SSH_KEY }}" > "$HOME/.ssh/id_rsa"
          chmod 600 "$HOME/.ssh/id_rsa"
          ssh-keyscan -t rsa ${{ secrets.FTP_SERVER }} >> "$HOME/.ssh/known_hosts"
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: Deploy to Main
        run: |
          ssh -i "$HOME/.ssh/id_rsa" ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }} "cd ~/www/${{ secrets.SITE_LOCATION }} && git pull"